from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected 1 match, found {count}")
    return text.replace(old, new)

# Stronger SDL drag state: Windows global state bypasses a stale per-window
# button state, while capture keeps button-up delivery reliable outside the window.
sdl = Path("src/sdl_utils.h")
text = sdl.read_text(encoding="utf-8")
text = replace_once(text, '''inline bool is_middle_mouse_button_down()\n{\n    return ( SDL_GetMouseState( nullptr, nullptr ) & SDL_BUTTON( SDL_BUTTON_MIDDLE ) ) != 0;\n}\n''', '''inline bool is_middle_mouse_button_down()\n{\n#if defined(_WIN32)\n    // SDL's per-window state can remain stale if a release is missed outside the\n    // window.  The global query asks Windows for the current physical state.\n    return ( SDL_GetGlobalMouseState( nullptr, nullptr ) & SDL_BUTTON( SDL_BUTTON_MIDDLE ) ) != 0;\n#else\n    return ( SDL_GetMouseState( nullptr, nullptr ) & SDL_BUTTON( SDL_BUTTON_MIDDLE ) ) != 0;\n#endif\n}\n\ninline bool has_sdl_mouse_focus()\n{\n    return SDL_GetMouseFocus() != nullptr;\n}\n\ninline void set_sdl_mouse_capture( const bool capture )\n{\n    // Capture makes SDL continue delivering motion/button-up while dragging\n    // beyond the window edge.  Failure is harmless; the physical-state guard\n    // still self-corrects the latched drag on the next input event.\n    SDL_CaptureMouse( capture ? SDL_TRUE : SDL_FALSE );\n}\n''', "sdl mouse helper")
sdl.write_text(text, encoding="utf-8")

# Gameplay map pan state.
game = Path("src/game.cpp")
text = game.read_text(encoding="utf-8")
text = replace_once(text, '''    const bool middle_mouse_down = is_middle_mouse_button_down();\n    if( camera_pan_active && !middle_mouse_down ) {\n        camera_pan_active = false;\n        camera_pan_anchor.reset();\n    }\n    if( action == "MOUSE_MOVE" && !camera_pan_active && middle_mouse_down ) {\n        camera_pan_anchor = ctxt.get_coordinates( w_terrain, ter_view_p.raw().xy(), true );\n        camera_pan_active = camera_pan_anchor.has_value();\n        if( camera_pan_active ) {\n            liveview.hide();\n        }\n        return true;\n    }\n    if( action == "CAMERA_PAN_START" ) {\n        camera_pan_anchor = ctxt.get_coordinates( w_terrain, ter_view_p.raw().xy(), true );\n        camera_pan_active = camera_pan_anchor.has_value();\n        if( camera_pan_active ) {\n            liveview.hide();\n        }\n        return true;\n    } else if( action == "CAMERA_PAN_END" ) {\n        camera_pan_active = false;\n        camera_pan_anchor.reset();\n        liveview.hide();\n        return true;\n''', '''    const bool middle_mouse_down = is_middle_mouse_button_down();\n    const bool mouse_focused = has_sdl_mouse_focus();\n    if( camera_pan_active && ( !middle_mouse_down || !mouse_focused ) ) {\n        camera_pan_active = false;\n        camera_pan_anchor.reset();\n        set_sdl_mouse_capture( false );\n    }\n    if( action == "MOUSE_MOVE" && !camera_pan_active && middle_mouse_down && mouse_focused ) {\n        camera_pan_anchor = ctxt.get_coordinates( w_terrain, ter_view_p.raw().xy(), true );\n        camera_pan_active = camera_pan_anchor.has_value();\n        if( camera_pan_active ) {\n            set_sdl_mouse_capture( true );\n            liveview.hide();\n        }\n        return true;\n    }\n    if( action == "CAMERA_PAN_START" ) {\n        camera_pan_anchor = ctxt.get_coordinates( w_terrain, ter_view_p.raw().xy(), true );\n        camera_pan_active = camera_pan_anchor.has_value();\n        if( camera_pan_active ) {\n            set_sdl_mouse_capture( true );\n            liveview.hide();\n        } else {\n            set_sdl_mouse_capture( false );\n        }\n        return true;\n    } else if( action == "CAMERA_PAN_END" ) {\n        camera_pan_active = false;\n        camera_pan_anchor.reset();\n        set_sdl_mouse_capture( false );\n        liveview.hide();\n        return true;\n''', "game pan state")
text = replace_once(text, '''#if defined(TILES)\n        camera_pan_active = false;\n        camera_pan_anchor.reset();\n#endif\n''', '''#if defined(TILES)\n        camera_pan_active = false;\n        camera_pan_anchor.reset();\n        set_sdl_mouse_capture( false );\n#endif\n''', "game non-mouse pan reset")
game.write_text(text, encoding="utf-8")

veh = Path("src/veh_interact.cpp")
text = veh.read_text(encoding="utf-8")

# Never leave global mouse capture behind when the editor closes.
text = replace_once(text, 'veh_interact::~veh_interact() = default;\n', '''veh_interact::~veh_interact()\n{\n#if defined(TILES)\n    set_sdl_mouse_capture( false );\n#endif\n}\n''', "vehicle destructor")

# Draw in the same world-facing coordinate system used by vehicle placement.
text = replace_once(text, '''point veh_interact::mount_to_viewport( const point_rel_ms &mount ) const\n{\n    const point cell = viewport_cell_size();\n    const point center( getmaxx( w_disp ) / 2, getmaxy( w_disp ) / 2 );\n    const point grid_mount = mount.rotate( 3 ).raw();\n    const point grid_center = viewport_center_mount.rotate( 3 ).raw();\n    return center + viewport_pan + point( ( grid_mount.x - grid_center.x ) * cell.x,\n                                          ( grid_mount.y - grid_center.y ) * cell.y );\n}\n''', '''point veh_interact::mount_to_viewport( const point_rel_ms &mount ) const\n{\n    const point cell = viewport_cell_size();\n    const point center( getmaxx( w_disp ) / 2, getmaxy( w_disp ) / 2 );\n\n    // Use the exact live mount-to-map transform used by vehicle placement and\n    // construction checks.  The editor therefore stays north-up and the vehicle\n    // appears in the same direction it actually occupies in the world.\n    const point grid_mount = veh->coord_translate( mount ).raw();\n    const point grid_center = veh->coord_translate( viewport_center_mount ).raw();\n    return center + viewport_pan + point( ( grid_mount.x - grid_center.x ) * cell.x,\n                                          ( grid_mount.y - grid_center.y ) * cell.y );\n}\n''', "mount_to_viewport")

# coord_translate includes discrete vehicle rotation, so use the forward transform
# itself for hit testing rather than trying to analytically invert a rounded tileray.
start = text.index('std::optional<point_rel_ms> veh_interact::viewport_to_mount( const point &screen ) const\n{')
end = text.index('\nvoid veh_interact::center_viewport_on_vehicle()', start)
old = text[start:end]
new = '''std::optional<point_rel_ms> veh_interact::viewport_to_mount( const point &screen ) const\n{\n    if( screen.x < 0 || screen.y < 1 || screen.x >= getmaxx( w_disp ) ||\n        screen.y >= getmaxy( w_disp ) ) {\n        return std::nullopt;\n    }\n\n    constexpr int editor_margin = 4;\n    const bounding_box bounds = veh->get_bounding_box( false, true );\n    const point cell = viewport_cell_size();\n    std::optional<point_rel_ms> best_mount;\n    long long best_distance = LLONG_MAX;\n\n    for( int x = bounds.p1.x() - editor_margin; x <= bounds.p2.x() + editor_margin; ++x ) {\n        for( int y = bounds.p1.y() - editor_margin; y <= bounds.p2.y() + editor_margin; ++y ) {\n            const point_rel_ms mount( x, y );\n            const point projected = mount_to_viewport( mount );\n            const long long dx = static_cast<long long>( screen.x - projected.x ) * cell.y;\n            const long long dy = static_cast<long long>( screen.y - projected.y ) * cell.x;\n            const long long distance = dx * dx + dy * dy;\n            if( distance < best_distance ) {\n                best_distance = distance;\n                best_mount = mount;\n            }\n        }\n    }\n\n    return best_mount;\n}\n'''
text = text[:start] + new + text[end:]

# Pan bounds must use the same facing projection as drawing.
text = replace_once(text, '''    for( const point_rel_ms &corner : corners ) {\n        const point grid = corner.rotate( 3 ).raw();\n        min_grid_x = std::min( min_grid_x, grid.x );\n        max_grid_x = std::max( max_grid_x, grid.x );\n        min_grid_y = std::min( min_grid_y, grid.y );\n        max_grid_y = std::max( max_grid_y, grid.y );\n    }\n\n    const point grid_center = viewport_center_mount.rotate( 3 ).raw();\n''', '''    for( const point_rel_ms &corner : corners ) {\n        const point grid = veh->coord_translate( corner ).raw();\n        min_grid_x = std::min( min_grid_x, grid.x );\n        max_grid_x = std::max( max_grid_x, grid.x );\n        min_grid_y = std::min( min_grid_y, grid.y );\n        max_grid_y = std::max( max_grid_y, grid.y );\n    }\n\n    const point grid_center = veh->coord_translate( viewport_center_mount ).raw();\n''', "pan bounds facing")

# Rotate curses part glyphs as the game does when the vehicle faces the world.
text = text.replace('veh->get_display_of_tile( vp.mount, false, false )',
                    'veh->get_display_of_tile( vp.mount, true, false )')
text = text.replace('veh->get_display_of_tile( selected_mount(), false, false )',
                    'veh->get_display_of_tile( selected_mount(), true, false )')

# Stronger editor drag capture/state guard.
text = replace_once(text, '''#if defined(TILES)\n    const bool middle_mouse_down = is_middle_mouse_button_down();\n    if( viewport_dragging && !middle_mouse_down ) {\n        viewport_dragging = false;\n    }\n    if( action == "MOUSE_MOVE" && !viewport_dragging && middle_mouse_down && viewport_pos ) {\n        viewport_dragging = true;\n        viewport_drag_anchor = *viewport_pos;\n        viewport_drag_pan_origin = viewport_pan;\n        return true;\n    }\n#endif\n\n    if( action == "CAMERA_PAN_START" ) {\n        if( viewport_pos ) {\n            viewport_dragging = true;\n            viewport_drag_anchor = *viewport_pos;\n            viewport_drag_pan_origin = viewport_pan;\n            return true;\n        }\n        return false;\n    }\n    if( action == "CAMERA_PAN_END" ) {\n        if( viewport_dragging ) {\n            viewport_dragging = false;\n            return true;\n        }\n        return false;\n    }\n''', '''#if defined(TILES)\n    const bool middle_mouse_down = is_middle_mouse_button_down();\n    const bool mouse_focused = has_sdl_mouse_focus();\n    if( viewport_dragging && ( !middle_mouse_down || !mouse_focused ) ) {\n        viewport_dragging = false;\n        set_sdl_mouse_capture( false );\n    }\n    if( action == "MOUSE_MOVE" && !viewport_dragging && middle_mouse_down && mouse_focused &&\n        viewport_pos ) {\n        viewport_dragging = true;\n        viewport_drag_anchor = *viewport_pos;\n        viewport_drag_pan_origin = viewport_pan;\n        set_sdl_mouse_capture( true );\n        return true;\n    }\n#endif\n\n    if( action == "CAMERA_PAN_START" ) {\n        if( viewport_pos ) {\n            viewport_dragging = true;\n            viewport_drag_anchor = *viewport_pos;\n            viewport_drag_pan_origin = viewport_pan;\n#if defined(TILES)\n            set_sdl_mouse_capture( true );\n#endif\n            return true;\n        }\n        return false;\n    }\n    if( action == "CAMERA_PAN_END" ) {\n        if( viewport_dragging ) {\n            viewport_dragging = false;\n#if defined(TILES)\n            set_sdl_mouse_capture( false );\n#endif\n            return true;\n        }\n#if defined(TILES)\n        set_sdl_mouse_capture( false );\n#endif\n        return false;\n    }\n''', "vehicle pan state")

veh.write_text(text, encoding="utf-8")
