from pathlib import Path

path = Path('src/veh_interact.cpp')
text = path.read_text()

old_controls = '''    if( open_editor_dropdown != editor_dropdown::none ) {\n        int x = 0;\n        int y = 0;\n        int width = 0;\n        int height = 0;\n        editor_dropdown_geometry( open_editor_dropdown, x, y, width, height );\n        if( pos.x >= x && pos.x < x + width && pos.y >= y && pos.y < y + height ) {\n            const int option = pos.y - y - 1;\n            if( option >= 0 && option < height - 2 ) {\n                if( open_editor_dropdown == editor_dropdown::system ) {\n                    active_system_filter = static_cast<editor_system_filter>( option );\n                    if( install_info ) {\n                        install_info->dirty = true;\n                    }\n                } else {\n                    active_condition_filter = static_cast<editor_condition_filter>( option );\n                }\n                open_editor_dropdown = editor_dropdown::none;\n                reset_part_selection();\n            }\n            return true;\n        }\n        open_editor_dropdown = editor_dropdown::none;\n        return true;\n    }\n'''
new_controls = '''    if( open_editor_dropdown != editor_dropdown::none ) {\n        int x = 0;\n        int y = 0;\n        int width = 0;\n        int height = 0;\n        editor_dropdown_geometry( open_editor_dropdown, x, y, width, height );\n        if( pos.x >= x && pos.x < x + width && pos.y >= y && pos.y < y + height ) {\n            const int option = pos.y - y - 1;\n            if( option >= 0 && option < height - 2 ) {\n                if( open_editor_dropdown == editor_dropdown::system ) {\n                    active_system_filter = static_cast<editor_system_filter>( option );\n                    if( install_info ) {\n                        install_info->dirty = true;\n                    }\n                } else {\n                    active_condition_filter = static_cast<editor_condition_filter>( option );\n                }\n                open_editor_dropdown = editor_dropdown::none;\n                reset_part_selection();\n            }\n            return true;\n        }\n        // Clicking outside the dropdown dismisses it, but do not consume the\n        // click here.  The normal mouse router still needs the same click so a\n        // schematic tile can be selected immediately instead of requiring a\n        // second click.\n        open_editor_dropdown = editor_dropdown::none;\n        return false;\n    }\n'''
if text.count(old_controls) != 1:
    raise SystemExit(f'controls block count={text.count(old_controls)}')
text = text.replace(old_controls, new_controls, 1)

old_select = '''        if( viewport_pos && handle_editor_controls_click( *viewport_pos ) ) {\n            return true;\n        }\n        if( open_editor_dropdown != editor_dropdown::none ) {\n            open_editor_dropdown = editor_dropdown::none;\n            return true;\n        }\n        if( over_schematic_content ) {\n'''
new_select = '''        if( viewport_pos && handle_editor_controls_click( *viewport_pos ) ) {\n            return true;\n        }\n        if( open_editor_dropdown != editor_dropdown::none ) {\n            open_editor_dropdown = editor_dropdown::none;\n            const bool click_selects_schematic = over_schematic_content;\n            const bool click_selects_part = !install_info && parts_pos && parts_pos->y >= 3;\n            if( !click_selects_schematic && !click_selects_part ) {\n                return true;\n            }\n            // Selection targets get click-through semantics: dismiss the open\n            // dropdown and apply this same left click to the tile/part below it.\n        }\n        if( over_schematic_content ) {\n'''
if text.count(old_select) != 1:
    raise SystemExit(f'select block count={text.count(old_select)}')
text = text.replace(old_select, new_select, 1)

path.write_text(text)
print('vehicle dropdown click-through fixed')
