from pathlib import Path

path = Path('src/veh_interact.cpp')
text = path.read_text()

old = '''    if( action == "SEC_SELECT" && !remove_info ) {\n        close_editor_context_menu();\n\n        if( !install_info && parts_pos ) {\n            if( parts_pos->y >= 3 ) {\n                const std::vector<int> parts = inspector_parts();\n                const int row = part_scroll + parts_pos->y - 3;\n                if( row >= 0 && row < static_cast<int>( parts.size() ) ) {\n                    selected_part = parts[row];\n                    part_detail_scroll = 0;\n                    open_editor_context_menu( here, *parts_pos, editor_context_surface::parts );\n                }\n            }\n            return true;\n        }\n\n        if( over_schematic_content ) {\n            if( const std::optional<point_rel_ms> mount = viewport_to_mount( *viewport_pos ) ) {\n                select_mount( here, *mount );\n                open_editor_context_menu( here, *viewport_pos, editor_context_surface::viewport );\n            }\n            return true;\n        }\n        return install_info && list_pos;\n    }\n'''

new = '''    if( action == "SEC_SELECT" && !remove_info ) {\n        // Do not pre-close an existing context menu here.  open_editor_context_menu()\n        // owns cross-surface replacement so it can redraw the old w_disp/w_parts\n        // surface before placing the new menu.  Pre-closing here loses that state\n        // and can leave the old menu pixels visible beside the new one.\n        if( !install_info && parts_pos ) {\n            if( parts_pos->y >= 3 ) {\n                const std::vector<int> parts = inspector_parts();\n                const int row = part_scroll + parts_pos->y - 3;\n                if( row >= 0 && row < static_cast<int>( parts.size() ) ) {\n                    selected_part = parts[row];\n                    part_detail_scroll = 0;\n                    open_editor_context_menu( here, *parts_pos, editor_context_surface::parts );\n                    return true;\n                }\n            }\n            close_editor_context_menu();\n            open_editor_dropdown = editor_dropdown::none;\n            return true;\n        }\n\n        if( over_schematic_content ) {\n            if( const std::optional<point_rel_ms> mount = viewport_to_mount( *viewport_pos ) ) {\n                select_mount( here, *mount );\n                open_editor_context_menu( here, *viewport_pos, editor_context_surface::viewport );\n                return true;\n            }\n            close_editor_context_menu();\n            open_editor_dropdown = editor_dropdown::none;\n            return true;\n        }\n\n        // A secondary click anywhere else dismisses the current transient menu.\n        close_editor_context_menu();\n        open_editor_dropdown = editor_dropdown::none;\n        return install_info && list_pos;\n    }\n'''

count = text.count(old)
if count != 1:
    raise SystemExit(f'expected one SEC_SELECT block, got {count}')
path.write_text(text.replace(old, new, 1))
print('vehicle context menu switch ordering fixed')
